name: Increment Version
on: workflow_dispatch
permissions:
  contents: write
jobs:
  increment-version:
#    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Output Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"
      - uses: actions/checkout@v3
      - name: Setup Git
        run: |
          git config --global user.name 'Auto Increment'
          git config --global user.email 'lucas42@users.noreply.github.com'
      - name: Increment Version
        run: npm version patch
#      - name: Commit
#        run: git push --follow-tags